# Generated by Django 3.2.7 on 2021-09-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GoalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField()),
                ('goal_set_datetime', models.DateTimeField(verbose_name='date published')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfit.exercisetype')),
                ('goal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfit.goaltype')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('datetime', models.DateTimeField(verbose_name='date published')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jfit.exercisetype')),
            ],
        ),
    ]
