# Generated by Django 3.2.7 on 2021-10-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_set_datetime',
            field=models.DateTimeField(),
        ),
    ]
