# Generated by Django 3.2.7 on 2021-10-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfit', '0002_auto_20211001_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_set_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
